- name: Push main to public repo
  run: |
    git remote add public https://x-access-token:${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/ehimshr/AI_EmailAssitant_Himanshu.git
    git push public main --force